name: cron

on:
  schedule:
    # every 12 hour
    - cron: 0 */12 * * *


jobs:
  fetch_campus_reputation:
    runs-on: ubuntu-latest
    steps:
      - name: STA 103
        run: |
          curl "https://us-central1-ucdstat.cloudfunctions.net/CampusWire/?course=sta103&secret=$STA103SECRET"
        env:
          STA103SECRET: ${{secrets.STA103SECRET}}
        shell: bash
