name: cron

# on:
#   schedule:
#     # every six hour
#     # - cron: 0 */6 * * *
#     - cron: '* * * * *'
on: [push, pull_request]


jobs:
  fetch_campus_reputation:
    runs-on: ubuntu-latest
    steps:
      - name: STA 103
        run: |
          curl --silent --show-error --fail https://us-central1-ucdstat.cloudfunctions.net/CampusWire/?course=sta103&secret=$STA103SECRET
        env:
          STA103SECRET: ${{secrets.STA103SECRET}}
