name: update campuswire reputation

# on:
#   schedule:
#     # every 12 hour
#     - cron: 0 */12 * * *

on: push

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go run main.go
