name: update campuswire reputation

on:
  schedule:
    # every 12 hour
    - cron: 0 */12 * * *

# on: push

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: run go script
        run: go run main.go
        env:
          SHEETID: ${{secrets.SHEETID}}
          SHEETSECRET: ${{secrets.SHEETSECRET}}
          CWTOKEN: ${{secrets.CWTOKEN}}
      - name: Create an issue
        if: ${{ failure() }}
        uses: maxkomarychev/oction-create-issue@v0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Failure"
