name: cron

on:
  schedule:
    # every six hour
    # - cron: 0 */6 * * *
    - cron: '* * * * *'

jobs:
  fetch_campus_reputation:
    runs-on: ubuntu-latest
    steps:
      - name: STA103
        run: |
          curl https://us-central1-ucdstat.cloudfunctions.net/CampusWire/?course=sta103&secret=$SECRET
        env:
          SECRET: ${{secrets.SECRET}}
